### ISSUE TITLE
Include statement of audience

### ISSUE THREAD

**Issue by djmitche** [maximtrp/scikit-posthocs#13]
The JOSS review requirements include:
> Do the authors clearly state what problems the software is designed to solve and who the target audience is?

The first part is covered in the documentation (and covered better in the paper - it might make sense to use that longer paragraph in the documentation as well).  However, neither the documentation nor the paper describe the target audience.

My understanding of that requirement is that I, as a reader, should be able to quickly determine "is this for me".  For example, is this useful for post-hoc tests on analyses done in other statistical systems such as SAS?  Does it support post-hoc tests for analyses other than ANOVA?

**Comment by djmitche** [comment]
(JOSS review is https://github.com/openjournals/joss-reviews/issues/1169)

**Comment by maximtrp** [comment]
@djmitche I tried to clarify what package does and who the target audience is.

**Comment by djmitche** [comment]
Looks great :+1:
