### ISSUE TITLE
Example usage appears only in README

### ISSUE THREAD

**Issue by djmitche** [maximtrp/scikit-posthocs#15]
https://scikit-posthocs.readthedocs.io/ does not appear to contain the examples that are featured in the README.  If it's easily done and maintained, it might be helpful for new users to find examples in whichever place they encounter first.

(For https://github.com/openjournals/joss-reviews/issues/1169)

**Comment by maximtrp** [comment]
I have added examples to the docs. Planning to add examples per each API section.

**Comment by maximtrp** [comment]
@djmitche I have updated the documentation

**Comment by djmitche** [comment]
:ok_hand: very nice
