### ISSUE TITLE
Error when running Friedman Conover test.

### ISSUE THREAD

**Issue by Leicas** [maximtrp/scikit-posthocs#19]
Hi

When I try to run a Conover posthoc on my pandas dataframe I get the following error:
/opt/conda/lib/python3.6/site-packages/scikit_posthocs/_posthocs.py:705: RuntimeWarning: invalid value encountered in sqrt
  tval = dif / np.sqrt(A / B)

I also suspect the Nemenyi to be affected as I am getting values of 0.001 exactly for every conditions.

Best,

**Comment by maximtrp** [comment]
Thank you for your bug report. Please post a reproducible example (code + dataset).

**Comment by Leicas** [comment]
I unfortunately cannot share my data now but will try to make a reproducible example.

After investigating, the error is cased by a negative value of A, thus the sqrt fail.
Further inspection suggest that the (1 - T1 / (k * (n-1)) is the reason, T1=285.79 in my case, k is 4 and n is 12.


It seems that the implementation in https://github.com/cran/PMCMRplus/blob/master/R/frdAllPairsConoverTest.R is totally different than the old one in PMCMR, I'm trying to see if that would solve the issue but my knowledge of R is to limited...

**Comment by maximtrp** [comment]
@Leicas I have updated the code. Please check if it is working now.

**Comment by Leicas** [comment]
No more error, some differences in the p-values but that was expected as it's a different calculation.

Thanks !

**Comment by mlpotter** [comment]
I would like to reopen this issue.

I am getting NaN's in the posthoc_conover_friedman test on all off-diagonal elements of the returned DataFrame. None of my values in the passed in DataFrame are NaN, nor negative.

I am using scikit-posthoc version 0.10.0

**Comment by maximtrp** [comment]
@mlpotter Could you please provide a minimal reproducible example (code + dataset)?
