### ISSUE TITLE
JOSS Review: Clarify Statement of need

### ISSUE THREAD

**Issue by mnarayan** [maximtrp/scikit-posthocs#20]
This is related to #18 as well. The package introduction and documentation assumes that the audience knows a great deal about pairwise multiple comparisons that arise after conducting an ANOVA. However, these scenarios are quite different from other sorts of multiple testing comparisons that arise. 

It would be great to provide a canonical example/scenario that a user can relate to.
Relevant to https://github.com/openjournals/joss-reviews/issues/1169

**Comment by maximtrp** [comment]
@mnarayan I have made numerous improvements to code, documentation, and docstrings, as well as drawn a flowchart and written two short tutorials. I hope this is enough.

**Comment by mnarayan** [comment]
The changes look good.
