### ISSUE TITLE
Where can I find the required inputs of function 'posthoc_nemenyi_friedman()' ?

### ISSUE THREAD

**Issue by AnyBrother** [maximtrp/scikit-posthocs#22]
Where can I find the required inputs of function 'posthoc_nemenyi_friedman()' ?
I cannot successful run 'posthoc_nemenyi_friedman()' cause I cannot figure out what should I feed into this function. An example is better if you are convenient, thanks a lot.

**Comment by maximtrp** [comment]
I have written a [short tutorial](https://github.com/maximtrp/scikit-posthocs#block-design) for block design data. Please tell me if it helped you to understand how to use the function arguments.

**Comment by AnyBrother** [comment]
Thanks a lot, it is quite helpful, wonderful work!
