### ISSUE TITLE
sign_plot significance order

### ISSUE THREAD

**Issue by tarikaltuncu** [maximtrp/scikit-posthocs#23]
Hi there!

Thanks for the nice library!

A small thing to suggest on sign_plot method, I believe it's better to put legend in the order to ['NS', 'p<0.05', 'p<0.01', 'p<0.001'] rather than the current version with 'NS' at the end. Because 'NS' is the situation where p>0.05, and it's more logical to sort the colormap on either descending or ascending order.

Best

**Comment by tarikaltuncu** [comment]
One more tiny suggestion, if someone could change the default colour for red to something less saturated (pink?) scale could be easily understandable on b&w prints.

Thanks!

**Comment by maximtrp** [comment]
@tarikaltuncu
Hey! Thank you for suggestions!

I have already pushed a [commit](https://github.com/maximtrp/scikit-posthocs/commit/6ac0f42e2c89a305d36b45aa57e5ae66f591feb9) changing the order of entries in the legend.

Could you provide a hex code of the color?

**Comment by tarikaltuncu** [comment]
Quite fast! Thanks @maximtrp!

What do you think for #fac4bf ? It's the darkest shade which would still be seen lighter than p<0.05  (#a1d99b) on b&w.

Best,

**Comment by maximtrp** [comment]
@tarikaltuncu Nice one. Thank you! It is [set by default](https://github.com/maximtrp/scikit-posthocs/commit/0eb57c7c1fd85d3e7a3036d7be03e29a86c2fb0b) now.

**Comment by tarikaltuncu** [comment]
Great! Thank you @maximtrp
