### ISSUE TITLE
Second code block in README doesn't work

### ISSUE THREAD

**Issue by fomightez** [maximtrp/scikit-posthocs#26]
I tried running the first two code blocks in the README and it fails with an error about `NameError: name 'Sepal' is not defined` at the following line:

```python
lm = sfa.ols('Sepal.Width ~ C(Species)', data=df).fit()
```

This works:

```python
lm = sfa.ols('df["Sepal.Width"] ~ C(Species)', data=df).fit()
```

I think the issue is that the column names clash with Pandas attribute notation (a.k.a 'dot notation'). However, adding in the bracket notation probably doesn't look like the R-style formula it is based on. Maybe renaming the columns would be a good compromise that keeps the R-like style formula more intact?  
Below works:

```python
df = df.rename(columns={'Sepal.Width':'SepalWidth'})
lm = sfa.ols('SepalWidth ~ C(Species)', data=df).fit()
```

**Comment by maximtrp** [comment]
Thank you for reporting this! I guess this is due to some changes in `statsmodels`. The code worked some time ago. I have added a line to correct columns names:
```
df.columns = df.columns.str.replace('.', '')
```
And replaced all occurrences of `Sepal.Width` with `SepalWidth`.
