### ISSUE TITLE
posthoc_dscf Calculation

### ISSUE THREAD

**Issue by Tsuchihashi-ryo** [maximtrp/scikit-posthocs#29]
in definition posthoc_dscf, ni and nj have been replaced.
CURRENT
```
def posthoc_dscf(a, val_col=None, group_col=None, sort=False):
....
　　def compare(i, j):
　　　　....
   　　　　     u = np.array([nj * ni + (nj * (nj + 1) / 2), 
　　　　　　　　　　　　nj * ni + (ni * (ni + 1) / 2)]) - r
　　　　....
```
TRUTH
```
 u = np.array([nj * ni + (ni * (ni + 1) / 2), 
　　　　　　nj * ni + (nj* (nj + 1) / 2)]) - r
```

**Comment by maximtrp** [comment]
Thank you for reporting. As you can see, `u` is only used to [calculate minimum](https://github.com/maximtrp/scikit-posthocs/blob/672620b08e1fc311e4b494db5eb73edbd9f765ba/scikit_posthocs/_posthocs.py#L2300), so the order is not important.

**Comment by Tsuchihashi-ryo** [comment]
Thank you for your answer. But `r` is for [i, j] and np.array in `u` is for [j, i]. In fact, I tried posthoc_dscf, then the false answer returned.

**Comment by maximtrp** [comment]
@Tsuchihashi-ryo 
Could you please post your input data and the results you obtained? What software package are you using as a reference?

**Comment by Tsuchihashi-ryo** [comment]
Thank you for checking.


data
|group|value|
|-----|------:|
|H2   | 28.033|
|F2   |  8.917|
|H2   | 30.000|
|F2   |  9.083|
|H2   | 30.000|
|F2   | 23.033|
|H2   | 30.000|
|CT   | 30.000|
|F2   |  7.483|
|H2   | 30.000|
|F2   | 30.000|
|CT   |  6.717|
|CT   | 28.067|
|CT   | 19.517|

posthoc_dscf output p value
|   |   CT   |  F2   |   H2   |
|---|-------:|------:|-------:|
|CT |-1.00000| 0.6510| 0.00888|
|F2 | 0.65103|-1.0000| 0.08649|
|H2 | 0.00888| 0.0865|-1.00000|

True p value(using R)
|   |   CT   |  F2   |   H2   |
|---|-------:|------:|-------:|
|CT |-1.00000| 0.9277126| 0.2413583|
|F2 | 0.9277126|-1.0000| 0.0864099|
|H2 | 0.2413583| 0.0864099|-1.00000|

`i` replaced `j` output p value
|   |  CT  |  F2   |  H2   |
|---|-----:|------:|------:|
|CT |-1.000|  0.900| 0.2416|
|F2 | 0.900| -1.000| 0.0865|
|H2 | 0.242|  0.086|-1.0000|

Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from scikit-posthocs) (1.17.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from scikit-posthocs) (3.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from scikit-posthocs) (1.4.1)
Requirement already satisfied: pandas>=0.20.0 in /usr/local/lib/python3.6/dist-packages (from scikit-posthocs) (0.25.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.6/dist-packages (from scikit-posthocs) (0.10.2)
Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from scikit-posthocs) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->scikit-posthocs) (1.1.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->scikit-posthocs) (2.6.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->scikit-posthocs) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->scikit-posthocs) (2.4.6)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.20.0->scikit-posthocs) (2018.9)
Requirement already satisfied: patsy>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from statsmodels->scikit-posthocs) (0.5.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from kiwisolver>=1.0.1->matplotlib->scikit-posthocs) (45.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.1->matplotlib->scikit-posthocs) (1.12.0)
Installing collected packages: scikit-posthocs
Successfully installed scikit-posthocs-0.6.2

**Comment by maximtrp** [comment]
You are right. Thank you! Fixed version is available.
