### ISSUE TITLE
pd.Grouper like group_col and level in the deep [enhancement]

### ISSUE THREAD

**Issue by Muilton** [maximtrp/scikit-posthocs#31]
Hello!

It would be great to check the difference between weeks. 
For example, 
posthoc_dunn(df, value='value', group_col=pd.Grouper(key='date', freq='W'))

where 'date' is DATE (by days or even hours) and freq='W' merges it by weeks. 

It will be useful when we want to find significant difference between weeks\days\months and etc. 

P.S. but it's not very important, because we can create new feature in  dataframe with this group (for example, df['date'].dt.week )

level in the deep.
it means if we send list with order of colums and can choose how many neighbors will be check.
of even dictionary where key is group and value is list with groups which we should compare. 
for example:
{group_1 : [group_2, group_3],
group_2 : [group_3, group_4]}

it will help to get less tax from p_adjust.

thanks

**Comment by maximtrp** [comment]
In my opinion, this is redundant and will possibly create a huge space for bugs. It is up to a user to create a grouping feature before analysis. Anyway, thank you for suggestion!
