### ISSUE TITLE
Negative p-value in the matrix

### ISSUE THREAD

**Issue by albertwibowo** [maximtrp/scikit-posthocs#33]
Hello, maybe this is not a bug. I am just wondering. I performed conover test after Kruskal-Wallis test and realise that In the matrix, the diagonal p-value is negative in value. Should it not be 1 because you are comparing a distribution to itself?

**Comment by maximtrp** [comment]
Hello! I agree this is not statistically correct. I added filling the diagonal with negative ones just for convenience, though it is not necessary for plotting functions now and obviously should be fixed. Thank you for drawing my attention to this problem!
