### ISSUE TITLE
[Feature Request] Make scikit-posthocs available from conda channels

### ISSUE THREAD

**Issue by marcelo-villa-p** [maximtrp/scikit-posthocs#34]
I tried to install the package using `conda` without luck. Many of my projects use `conda` environments and `environment.yml` files to setup and install every package needed. This package could be available from `conda-forge`, for example.

**Comment by maximtrp** [comment]
Thank you! I have made a pull request to add `scikit-posthocs` to `conda-forge`. The process usually takes some time.

**Comment by maximtrp** [comment]
The [package](https://anaconda.org/conda-forge/scikit-posthocs) is available for installing from conda-forge channel.
