### ISSUE TITLE
typo in posthocs.readthedocs.io doc

### ISSUE THREAD

**Issue by valosekj** [maximtrp/scikit-posthocs#35]
I found possible typo in posthocs.readthedocs.io documentation at the end of the Block design section for `sp.posthoc_nemenyi_friedman` test (https://scikit-posthocs.readthedocs.io/en/latest/tutorial/#block-design):

Should not be in command below `data` instead of `x`?

`sp.posthoc_nemenyi_friedman(x, y_col='y', block_col='blocks', group_col='groups', melted=True)`

**Comment by maximtrp** [comment]
Fixed. Thank you!
