### ISSUE TITLE
fail to import scikit_posthocs

### ISSUE THREAD

**Issue by yiexu** [maximtrp/scikit-posthocs#39]
Hi,

I have been using scikit_posthocs(Version: 0.6.6) in Python 3.7.1  for a while. Today, when I tried to import scikit_posthocs, I got an error as 
ModuleNotFoundError: No module named 'statsmodels.stats.libqsturng'

I checked with pip show statsmodels and Version: 0.12.0 was shown. I reinstalled by 'pip install statsmodels' but got the same error message. I reinstalled by 'pip install scikit-posthocs' but problem remained.
Running out of ideas. What could be the reason?

Thanks!

**Comment by maximtrp** [comment]
Hello! Could you please try to reinstall `statsmodels` with the following code?

```bash
pip uninstall statsmodels && pip install statsmodels
```

**Comment by yiexu** [comment]
Thanks so much! Everything is working now~

**Comment by maximtrp** [comment]
You are welcome!
