### ISSUE TITLE
scikit_posthocs.sign_plot showing significance text table

### ISSUE THREAD

**Issue by legolego** [maximtrp/scikit-posthocs#40]
Hi,
I just started using this library and like it so far, but I'm getting this text table out after calling scikit_posthocs.sign_plot. Is there a way to not have it show? Or what am I doing wrong? Thank you very much!
![image](https://user-images.githubusercontent.com/1666188/98823627-5afc0d80-2400-11eb-95ee-742465fe9d1f.png)

**Comment by maximtrp** [comment]
Thank you for reporting! It will be fixed in the next release
