### ISSUE TITLE
Is it possible to also return the test statistic instead of only p-values?

### ISSUE THREAD

**Issue by sandervalstar** [maximtrp/scikit-posthocs#41]
Hi, 

Thank you so much for this useful python package!

As I was running post-hoc tests I noticed the functions in scikit_posthocs only return p-values and do not return the test statistic value. Would it be possible to add that or is there a specific reason you left that out of the results table?

For example, when running Dunn's test using posthoc_dunn, I would like to also see the respective pairwise z test statistic in each cell in the results in table (similarly to the [dunn.test R package](https://cran.r-project.org/web/packages/dunn.test/dunn.test.pdf)).

Thank you!

**Comment by maximtrp** [comment]
Hello! I will add it in one of the future versions. Thank you for suggestion!
