### ISSUE TITLE
Add hypo argument for outliers_gesd

### ISSUE THREAD

**Issue by nateGeorge** [maximtrp/scikit-posthocs#43]
I'm happy to contribute this if you want, but it would be good to have a `hypo` argument for `outliers_gesd()` like with `outliers_tietjen()`. The reason being, when you get a boolean mask you can use that to deal with outliers as you like - for example, clipping them to max/min values and so on. This is important for cleaning outliers in multivariate datasets, which are pretty much all of them.

**Comment by maximtrp** [comment]
Thank you!
