### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by directorfury192** [maximtrp/scikit-posthocs#45]
I can download scikit-posthocs on my Python 3.7 machine but when I download it on the machine running Python 3.8, I keep getting error messages.  Using pip install scikit-posthocs

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))': /simple/scikit-posthocs/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))': /simple/scikit-posthocs/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))': /simple/scikit-posthocs/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))': /simple/scikit-posthocs/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))': /simple/scikit-posthocs/
Could not fetch URL https://pypi.org/simple/scikit-posthocs/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/scikit-posthocs/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))) - skipping
ERROR: Could not find a version that satisfies the requirement scikit-posthocs
ERROR: No matching distribution found for scikit-posthocs
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))) - skipping

**Comment by maximtrp** [comment]
Thank you for reporting it. But this issue is not related to scikit-posthocs. You can try to update `pip` with these commands:

```bash
curl https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
```

Also, [this issue](https://github.com/pypa/pip/issues/5063) seems to be relevant. If updating pip doesn't help, try to add PyPi hosts as trusted.
