### ISSUE TITLE
Rotation of the vertical ticks in the significance matrix. 

### ISSUE THREAD

**Issue by areyesromero** [maximtrp/scikit-posthocs#48]
Dear Maksim, thank you for creating this useful script. I would like to rotate the ticks on the vertical axis by 90 degrees. I tried to use g.tick_params(labelrotation=45) recalling g=sp.sign_plot() but 'tuple' object has no attribute 'tick_params'.
Can you help me better understand how to do this? Thanks in advance.
![example_matrix](https://user-images.githubusercontent.com/82033522/117647528-5afd8000-b18d-11eb-8cc0-224e9ede5ae8.png)

**Comment by maximtrp** [comment]
You were almost there: just unpack the returned tuple and use its first item:
```python
ax, cbar_ax = sp.sign_plot(data)
ax.tick_params(labelrotation=45)
```
