### ISSUE TITLE
Cannot import under python 2.7 by using Spyder

### ISSUE THREAD

**Issue by lidongren** [maximtrp/scikit-posthocs#50]
**Describe the bug**
I cannot import scikit_posthocs under python 2.7 by using Spyder. when I run the following code:
**import scikit_posthocs as sp**

It gives the following error:

**import scikit_posthocs as sp
  File "//anaconda2/lib/python2.7/site-packages/scikit_posthocs/_global.py", line 6
    def global_simes_test(x: Union[List, ndarray]) -> float:
                           ^
SyntaxError: invalid syntax**

Could you give a solution? Thanks.

**Comment by maximtrp** [comment]
Sorry, Python 2.7 support is discontinued.
