### ISSUE TITLE
Significance Plots Colour Bar Breaks Using Matplotlib >= 3.5.0

### ISSUE THREAD

**Issue by MattyB95** [maximtrp/scikit-posthocs#51]
It appears the way Matplotlib handles colour bars from version 3.5.0 breaks the significance plots colour bar:

**To Reproduce**

```
import matplotlib.pyplot as plt
import scikit_posthocs as sp
import statsmodels.api as sa

x = sa.datasets.get_rdataset('iris').data
x.columns = x.columns.str.replace('.', '')
pc = sp.posthoc_ttest(x, val_col='SepalWidth', group_col='Species', p_adjust='holm')
heatmap_args = {'linewidths': 0.25, 'linecolor': '0.5', 'clip_on': False, 'square': True,
                'cbar_ax_bbox': [0.82, 0.35, 0.04, 0.3]}
sp.sign_plot(pc, **heatmap_args)
plt.show()
```

![issue](https://user-images.githubusercontent.com/5563995/153777650-f26740e4-1eb9-461a-b87f-716fcd97d875.png)

**Expected behaviour**

![expected](https://user-images.githubusercontent.com/5563995/153777646-47399cba-04aa-4d07-859e-94ac8626b25c.png)

**Comment by maximtrp** [comment]
Thank you for this fix! I probably need to test the other functions. Time passes and third-party packages change their behavior.
