### ISSUE TITLE
Use posthoc tests to plot critical difference diagram

### ISSUE THREAD

**Issue by bangxiangyong** [maximtrp/scikit-posthocs#54]
It seems there are many post-hoc tests implemented and will be really good if there's an easy interface to plot critical difference diagrams with any chosen pairwise tests. 

In Orange framework, there's only few types of tests implemented and the interface isn't very intuitive.

**Comment by genos** [comment]
Seconded! I'd really like this feature—though I understand that this is a (wonderful!) open source library, and I'm lucky that it exists at all, and I shouldn't be demanding features.
