### ISSUE TITLE
[Feature request] outlier_gesd to return data even when report=True

### ISSUE THREAD

**Issue by ysBach** [maximtrp/scikit-posthocs#55]
I have found this package extremely useful for quantitative data analysis for my astronomical data. Especially outlier_gesd is a simple/powerful function for me at this specific moment.

While using it, I wonder why it "returns" a str when ``report=True``. My expectation was it prints out the report, while returning the same output as ``report=False``.

I wonder if this was an intention. :)

**Comment by maximtrp** [comment]
> While using it, I wonder why it "returns" a str when report=True. My expectation was it prints out the report, while returning the same output as report=False.
Yes, I agree, this is strange behavior. It will be better to always return an array and print report if necessary. Will add it in the next release. Thank you!
