### ISSUE TITLE
Wilcoxon paired test is not really paired

### ISSUE THREAD

**Issue by Denis-Kazakov** [maximtrp/scikit-posthocs#59]
scikit_posthocs.posthoc_wilcoxon implements Wilcoxon paired test, that is  measurements should be paired: before and after, different treatments on the same patient, etc.
The current implementation only uses two columns: var_col and group_col so the result depends on the order of rows in the dataframe.
There must be another variable to match measurements or the wide format should be used with each row giving measurements for the same item.

**Comment by maximtrp** [comment]
Thank you for this comment. This package is using `scipy.stats.wilcoxon` as a backend method. Method interface is equivalent to `pairwise.wilcox.test` in R. Could you refer to an implementation of what you are suggesting?
