### ISSUE TITLE
sign_plot error with underflowing p-values

### ISSUE THREAD

**Issue by bmcfee** [maximtrp/scikit-posthocs#6]
I noticed a quirk in `sign_plot` when inputting a p-value array whose entries had underflowed to 0.0F, presumably due to floating point precision.  The logic [here](https://github.com/maximtrp/scikit-posthocs/blob/master/scikit_posthocs/_plotting.py#L206-L210) maps 0 entries to `NS`, which is exactly what one would not want to happen.

I was able to hack around this by adding `1e-40` to the entries before rendering the plot, but it could be avoided altogether by moving [this line](https://github.com/maximtrp/scikit-posthocs/blob/master/scikit_posthocs/_plotting.py#L206) to the end, and changing [this line](https://github.com/maximtrp/scikit-posthocs/blob/master/scikit_posthocs/_plotting.py#L207) to use `df>=0`.

**Comment by maximtrp** [comment]
Fixed. Thank you!
