### ISSUE TITLE
custom comparisons on scikit_posthocs.posthoc_tukey

### ISSUE THREAD

**Issue by GEJ1** [maximtrp/scikit-posthocs#61]
I want to perform the Tukey test of comparisons for a subset of pairs.

The problem I face is that `scikit_posthocs.posthoc_tukey` works since I am interested in all possible comparisons. Therefore, the applied correction is based on all tests. However, I am only hypothesizing on a subset of pairs.

Do you plan to add this functionality?

Thank you very much,

Gustavo

**Comment by maximtrp** [comment]
Why not just filter your data to include the groups you are interested in? If you are aware of a specific procedure existing for that case, please reopen this issue.
