### ISSUE TITLE
Alpha cannot be specified for critical difference diagram

### ISSUE THREAD

**Issue by j-adamczyk** [maximtrp/scikit-posthocs#65]
**Describe the bug**

I haven't seen any way to provide alpha (0.05 or 0.1) for plotting critical difference diagram of Nemenyi-Friedman test. I'm trying to follow Demsar's paper [link](https://www.jmlr.org/papers/volume7/demsar06a/demsar06a.pdf) and [this tutorial (which sadly uses Orange package)](https://edisciplinas.usp.br/pluginfile.php/4129451/mod_resource/content/1/model_selection_evaluation.pdf#:~:text=For%20the%20comparison%20of%20multiple,their%20mean%20ranks%20are%20equal), and:
- "The performance of two classifiers is significantly different if the corresponding average ranks differ by at least the critical difference"
- "critical values q_α are based on the Studentized range statistic divided by √2", and examples of such values are provided in the paper
- [relevant scikit-posthocs code](https://github.com/maximtrp/scikit-posthocs/blob/18bc6a7f738298ae7cb62a4abfbbb1a01a7d803a/scikit_posthocs/_posthocs.py#L578)

So I get the p-values from the test. But looking at [CD plotting function](https://github.com/maximtrp/scikit-posthocs/blob/18bc6a7f738298ae7cb62a4abfbbb1a01a7d803a/scikit_posthocs/_plotting.py#L483), we can see that it uses `sign_array()` function with constant arguments, which is `alpha=0.05`. So there is no way to plot CD diagram with any other alpha level. This should be configurable.

**Comment by maximtrp** [comment]
Hello! Thank you for pointing at this. This test was based on statsmodels' implementation of Studentized range distribution. It is bound to 0.1, there is no way to specify alpha value. Now we have SciPy's implementation which should be more appropriate here.

**Comment by maximtrp** [comment]
Hopefully fixed in v0.10.0
