### ISSUE TITLE
Error with posthoc_conover_friedman

### ISSUE THREAD

**Issue by mlpotter** [maximtrp/scikit-posthocs#76]
**Describe the bug**
Similar to closed issue #19 , I am getting NaN's in the posthoc_conover_friedman test on all off-diagonal elements of the returned DataFrame. 

`sp.posthoc_conover_friedman(mse_df,p_adjust ="fdr_bh")`

None of my values in the passed in the `mse_df` dataframe are NaN, nor negative.

The columns of the `mse_df` are the machine learning models, the rows are the different datasets, and the values are a distance metric.

**Expected behavior**

**System and package information (please complete the following information):**
- OS: Rocky Linux (Green Obsidian)
- Package version:  0.10.0

I am using scikit-posthoc version 0.10.0

**Comment by maximtrp** [comment]
@mlpotter Thank you for reporting! Can I have a look at a reproducible example? If not, could you help me debug it by extracting a function implementing this test and printing out strange results on each step?

**Comment by mlpotter** [comment]
I am attaching a csv file with the dataframe, and minimal code to load in the dataframe and pass it to the posthoc_conover_friedman test. Please let me know if this works.

```
import pandas as pd
import scikit_posthocs as sp
test_df = pd.read_csv('test.csv',index_col=0).applymap(float)

print(test_df.head())
print(sp.posthoc_conover_friedman(test_df,p_adjust ="fdr_bh"))
```

[test.csv](https://github.com/user-attachments/files/17909680/test.csv)

**Comment by maximtrp** [comment]
@mlpotter Thank you! Attempted to this fix in the recent commit. Do you mind me adding this data to package tests?

**Comment by maximtrp** [comment]
The new version is released. Could you please try it?

**Comment by mlpotter** [comment]
> Thank you! Attempted to fix it in the recent commit. Do you mind me adding this data to the package tests?

You may add the data to the package tests! 

> The new version is released. Could you please try it?

I will try it this upcoming Monday! Thank you!

**Comment by mlpotter** [comment]
@maximtrp I created a new conda environment with python version `3.10`, and installed  `scikit_posthocs` version `0.11.0`. I ran the previously mentioned code on the same test.csv file.

Output below: 

```
            entropy  likely_failure     misdp    oldest    random
(0.7,0.8)  1.261300        0.598607  0.511320  0.548915  0.509370
(0.3,0.9)  0.525733        0.654802  0.483422  0.495560  0.449617
(0.6,0.9)  0.346409        0.253853  0.207595  0.223906  0.219041
(0.6,0.9)  0.185977        0.214178  0.171789  0.174240  0.171997
(0.4,0.9)  0.654265        0.630849  0.475334  0.488215  0.542571
                     entropy  likely_failure         misdp        oldest  \
entropy         1.000000e+00    1.576812e-06  1.513596e-22  6.852539e-02   
likely_failure  1.576812e-06    1.000000e+00  1.115656e-39  1.154285e-10   
misdp           1.513596e-22    1.115656e-39  1.000000e+00  8.928555e-17   
oldest          6.852539e-02    1.154285e-10  8.928555e-17  1.000000e+00   
random          1.056315e-13    1.710448e-29  4.538425e-03  5.084316e-09   

                      random  
entropy         1.056315e-13  
likely_failure  1.710448e-29  
misdp           4.538425e-03  
oldest          5.084316e-09  
random          1.000000e+00  
```

No more NaN values.  Thank you for updating the code!

**Comment by maximtrp** [comment]
@mlpotter Thank you for reporting!
