### ISSUE TITLE
Calls to critical_difference_diagram change the values in matrices of test results

### ISSUE THREAD

**Issue by Heptasphere** [maximtrp/scikit-posthocs#77]
**Describe the bug**
Methods using `sign_array` such as `critical_difference_diagram` modify the test results given to them.

**Dataset**
I generated the dataset in a way similar to the example provided in the tutorial: 
https://scikit-posthocs.readthedocs.io/en/latest/tutorial.html#critical-difference-diagrams

However, since there was an issue with `posthoc_conover_friedman`'s `block_id_cols`, I didn't use a melted dataset.

Generation:

```
rng = np.random.default_rng(1)
dict_data = {
    "model1": rng.normal(loc=0.2, scale=0.1, size=30),
    "model2": rng.normal(loc=0.2, scale=0.1, size=30),
    "model3": rng.normal(loc=0.4, scale=0.1, size=30),
    "model4": rng.normal(loc=0.5, scale=0.1, size=30),
    "model5": rng.normal(loc=0.7, scale=0.1, size=30),
    "model6": rng.normal(loc=0.7, scale=0.1, size=30),
    "model7": rng.normal(loc=0.8, scale=0.1, size=30),
    "model8": rng.normal(loc=0.9, scale=0.1, size=30),
}
data = pd.DataFrame(dict_data)
```

**To Reproduce**

After dataset generation, use a test and `critical_difference_diagram`.

```
avg_rank = data.rank(axis=1).mean()
test_results = sp.posthoc_conover_friedman(data)
```

At this point `test_result `should contain a lot of p-values different from 0 and 1.

Next, if we use `critical_difference_diagram`.

```
cdd = critical_difference_diagram(avg_rank, test_results)
```

At this point, `test_result `only contains 0s and 1s.

The same thing happens if the previous code snippet is replace with:

```
sign_array(test_results)
```

**Expected behavior**
`test_result` should continue to contain p-values after a critical difference diagram was created.

**System and package information (please complete the following information):**
- OS: Windows 11
- Package version: 0.11.0

**Additional context**
An easy fix seems to be to replace the first line of `sign_array` to make it create a copy.

Replacing:
```
p_values = np.array(p_values)
```
by:
```
p_values = np.copy(np.array(p_values))
```

**Comment by maximtrp** [comment]
Thank you for reporting! Fixed and released the new version.

**Comment by Heptasphere** [comment]
The issue was not fixed. The same case still has the same problem.

The changes made to correct this make a shallow copy of the pvalue matrix as described in https://numpy.org/doc/stable/reference/generated/numpy.array.html.

Using `copy.deepcopy` in `sign_array` at line 45 in `_plotting.py` seems to fix the problem.

```
from copy import deepcopy
...
    sig_array = copy.deepcopy(np.array(p_values))
```

Sorry it took so long to get back to this.

**Comment by maximtrp** [comment]
Thank you! Haven't checked if the copy is shallow. Will be included into the coming release
