### ISSUE TITLE
Minor Bug in sign_plot leads to all insignificant plot when using DataFrame

### ISSUE THREAD

**Issue by feiden** [maximtrp/scikit-posthocs#79]
**Describe the bug**
A call by reference in the sign_plot method leads to a bad plot if using a DataFrame.

**To Reproduce**
Minimal example:
```
import statsmodels.api as sa
import scikit_posthocs as sp
df = sa.datasets.get_rdataset('iris').data
post_hoc = sp.posthoc_ttest(df, val_col='Sepal.Width', group_col='Species', p_adjust='holm')
fig = sp.sign_plot(post_hoc, flat=False)[0].get_figure()
```

**Solution**
Change `xc = df.values` to `xc = df.values.copy()` in line 195 in plotting.py

**Last Words**
Thank you for this nice open source code :)

**Comment by maximtrp** [comment]
Hi! Thank you for reporting, but there is no bug. Please look at [line 194](https://github.com/maximtrp/scikit-posthocs/blob/3359fb5e00e56e50cb495d3bac6e8b27983c95f4/scikit_posthocs/_plotting.py#L194). DataFrames are being copied now, so no need for any other changes.

**Comment by feiden** [comment]
Hi Maxim, yes the dataframe is being copied as `df`, but `xc` is not copied from df. Later `df` (lines 224-227) is being changed based on the values of `xc`, but when changing `df`, `xc` changes too, leading to an error. You should be able to see that in the code example I provided, no? Maybe this error only occurs with certain versions, idk?

**Comment by feiden** [comment]
Maybe I should note, that it does not throw an error, but rather the values get incorrect

**Comment by maximtrp** [comment]
What version are you using?

**Comment by maximtrp** [comment]
Sorry, did not inspect it carefully. Should be fixed in the next release
